import React from 'react';
import PropTypes from 'prop-types';
import Doc from './Doc';
import './Docs.css';

/**
 * A component designed to display the info generated by react-docgen
 */
class Docs extends React.Component {

    render() {
        const comps = [];
        for (const component in this.props.data) {
            const obj = this.props.data[component];
            comps.push(<Doc component={component} key={component} obj={obj} />);
        }
        return (
            <div>
                <h1>React component docs</h1>
                <p>Below are all of the generated docs for this project's react components.</p>
                {comps}
            </div>
        )
    }
}

Docs.propTypes =  {
    /**
     * The data containing information about all react components in the project
     */
    data: PropTypes.object.isRequired
}

export default Docs
